# yaml-language-server: $schema=https://raw.githubusercontent.com/siemens/kas/66261547b75885786777a0b9c8a4400ab81d432e/kas/schema-kas.json
header:
  version: 1
local_conf_header:
  meta-common: |
    PACKAGE_CLASSES ?= "package_rpm"
    VOLATILE_LOG_DIR = "no"

    INIT_MANAGER="systemd"
    IMAGE_INSTALL:append = " \
      tedge \
      tedge-state-scripts \
    "
