# yaml-language-server: $schema=https://raw.githubusercontent.com/siemens/kas/66261547b75885786777a0b9c8a4400ab81d432e/kas/schema-kas.json
header:
  version: 14

local_conf_header:
  meta-mender-raspberrypi: |
    INHERIT += "mender-full"
    MENDER_ARTIFACT_NAME ?= "release-1"
    SYSTEMD_AUTO_ENABLE:pn-mender-client = "disable"
    RPI_USE_U_BOOT = "1"
    IMAGE_INSTALL:append = " kernel-image kernel-devicetree"
    IMAGE_FSTYPES:remove = " rpi-sdimg"
    SDIMG_ROOTFS_TYPE = "ext4"
    MENDER_BOOT_PART_SIZE_MB = "64"

    # Disable mender systemd dependency
    MENDER_FEATURES_DISABLE:append = " mender-systemd"

    # mender golang client 3.x
    #PREFERRED_PROVIDER_mender-native = "mender-client-native"
    #PREFERRED_RPROVIDER_mender-auth = "mender-client"
    #PREFERRED_RPROVIDER_mender-update = "mender-client"

    # mender cpp client >=4.x
    PREFERRED_PROVIDER_mender-native = "mender-native"
    PREFERRED_RPROVIDER_mender-auth = "mender"
    PREFERRED_RPROVIDER_mender-update = "mender"
