# yaml-language-server: $schema=https://raw.githubusercontent.com/siemens/kas/66261547b75885786777a0b9c8a4400ab81d432e/kas/schema-kas.json
header:
  version: 14
bblayers_conf_header:
  meta-mender: |
    POKY_BBLAYERS_CONF_VERSION = "2"
    BBPATH = "${TOPDIR}"
    BBFILES ?= ""

local_conf_header:
  meta-mender: |
    INHERIT += "mender-full"
    MENDER_ARTIFACT_NAME ?= "release-1"
    SYSTEMD_AUTO_ENABLE:pn-mender-client = "disable"
    IMAGE_FSTYPES:remove = " rpi-sdimg"
    SDIMG_ROOTFS_TYPE = "ext4"
    MENDER_BOOT_PART_SIZE_MB = "64"
